- src/frameworks/UBCryptoUtils.cpp
- src/frameworks/UBCryptoUtils.h
OpenSSL 1.1 has a new API. This commit allows to compile against it, as well
as it keeps compatibility with previous versions of OpenSSL.
> Add compatibility with OpenSSL 1.1

- resources/i18n/OpenBoard_de.ts
In German, "Kompass" is the navigational instrument. The drawing tool is called "Zirkel."
> Fix wrong German translation: "Kompass" -> "Zirkel"

- resources/etc/OpenBoard.css
Fixes ui with dark system themes
before:
after:
> OpenBoard.css: Add background color to QMenu, QPushButton and QComboBox

- resources/forms/mainWindow.ui
- resources/forms/preferences.ui
- src/board/UBBoardController.cpp
- src/board/UBBoardController.h
- src/board/UBBoardView.cpp
- src/core/UBPreferencesController.cpp
- src/core/UBSettings.cpp
- src/core/UBSettings.h
- src/desktop/UBDesktopPropertyPalette.cpp
- src/gui/UBToolbarButtonGroup.cpp
- src/gui/UBToolbarButtonGroup.h
**Configurable Shortcuts**
- Replaced Event Handler with QShortcuts
- Added logic to "rotate" colors and width
- Fixed names of main window elements, so they are deterministic
- Added preference setting for the shortcuts
- Added "Advanced" Tab in preferences to edit the shortcuts (a bit raw - might need some love)
Known issues:
- Upon startup no color is selected
- Ctrl-I was used for two actions - "Zoom In" and "Pen". Now only "Pen"
**Note:** I tried to split up in single commits to better comment on what I did - the single commits will not all build, however.
Reference/Inspiration: https://doc.qt.io/archives/qq/qq14-actioneditor.html
> PR shortcuts

- OpenBoard.pro
- src/api/UBLibraryAPI.h
- src/api/UBW3CWidgetAPI.cpp
- src/board/UBBoardController.cpp
- src/board/UBBoardPaletteManager.h
- src/core/UB.h
- src/core/UBApplication.cpp
- src/desktop/UBDesktopAnnotationController.cpp
- src/desktop/UBDesktopPalette.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsWidgetItem.h
- src/frameworks/UBPlatformUtils_mac.mm
- src/gui/UBFeaturesWidget.h
- src/gui/UBMainWindow.h
- src/network/UBCookieJar.cpp
- src/pdf/XPDFRenderer.h
- src/web/UBWebController.cpp
- src/web/UBWebController.h
- src/web/UBWebKitUtils.h
- src/web/browser/WBBrowserWindow.cpp
- src/web/browser/WBBrowserWindow.h
- src/web/browser/WBDownloadManager.cpp
- src/web/browser/WBHistory.cpp
- src/web/browser/WBHistory.h
- src/web/browser/WBTabWidget.h
- src/web/browser/WBToolBarSearch.cpp
- src/web/browser/WBWebTrapWebView.cpp
- src/web/browser/WBWebTrapWebView.h
- src/web/browser/WBWebView.cpp
- src/web/browser/WBWebView.h
Fixes current MAC desktop mode issues, by either allowing to compile with Qt5.9, or by updating the QGraphicsScene mask, as it is already done on Linux.
> Dev qt5.1x mac

- src/board/UBDrawingController.cpp
- src/board/UBDrawingController.h
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- Basically simulate a device release with the previous tool and a device press with the new tool to correctly terminate the previous action.
- Hide the eraser when switching to another tool.
- Add an additional guard against accessing an element of an empty list.
- Fixes #430 
- Fixes #354
> Detect and handle change of stylusTool while device pressed

- src/core/UBSettings.cpp
Pointer diameter is now configurable using the settings. Add e.g.
```
[Board]
PointerDiameter=20
```
to change the pointer diameter from the default size of 40 to 20.
Fixes #444
> Make pointer diameter configurable

- resources/i18n/OpenBoard_de.ts
Shortcuts are broken when using the German translation.
To fix this, this pull requests removes spaces from translation of shortcuts. Additionally it adds some missing translations.
Fixes #428
> Fix broken shortcuts with German translation

- OpenBoard.pro
- src/core/UBApplicationController.cpp
- src/core/UBApplicationController.h
- src/web/UBOEmbedParser.cpp
Allows to drop the deprecated QtScript dependency. QJSonDocument should provide better performance than QJSEngine from QtQml.
> Port from QScriptEngine to QJSonDocument

- src/document/UBDocumentController.cpp
- src/domain/UBGraphicsDelegateFrame.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsStrokesGroup.cpp
I did a valgrind run to try and figure out why it OpenBoard crashes from
time to time, and found these two uninitialized variable uses.
> fix a number of uninitialized variable uses

- src/domain/UBGraphicsScene.cpp
When computing the actual radius of the pointer, the `systemScaleFactor` is not included in the calculation. This simple PR fixes this.
Closes https://github.com/OpenBoard-org/OpenBoard/issues/444#issuecomment-798982133
> Take systemScaleFactor into account for pointer diameter

- resources/etc/OpenBoard.config
- src/core/UBApplication.cpp
- src/core/UBSettings.cpp
- src/core/UBSettings.h
- src/frameworks/UBPlatformUtils_linux.cpp
- src/frameworks/UBPlatformUtils_win.cpp
This patch is based on work by @fsckawk and @sagredo-dev in #327 and #340:
* removed the "RunInWindow patch" comments, because this is no longer "just a patch" :)
* removed additional ffmpeg include (which appears to be another bug, not related to this issue)
* fix indentation
My intent in opening this PR is to make sure the patch is not lost.  It still requires editing the configuration file, but this is significantly easier than building OpenBoard from source.
I think that will help OpenBoard users:
* use it with screen sharing software for remote learning
* use it with OBS or other video mixing software
* use it on computers with more than 2 monitors (if it's a window, it can be put anywhere)
There are [community OpenBoard builds with this or similar …
> Adds RunInWindow flag to OpenBoard

- src/core/UBApplicationController.cpp
- src/core/UBDisplayManager.cpp
- src/desktop/UBCustomCaptureWindow.cpp
- src/desktop/UBDesktopAnnotationController.cpp
Desktop mode did not work correctly when the display screen is positioned left to the control screen in a two-monitor setup. The reason is that global coordinates covering the complete desktop with multiple monitors are used as local coordinates in a widget at some places. This works as long as the control screen is located at (0,0), but leads to offsets if this is not the case.
- fix usage of global coordinates where local coordinates are required
- show widget before changing geometry (necessary in some environments)
This PR fixes https://github.com/letsfindaway/OpenBoard/issues/72 and https://github.com/letsfindaway/OpenBoard/issues/73 (minimal fix without rework of `UBDisplayManager`).
> fix: coordinates when display screen is left of control screen

- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/board/UBBoardPaletteManager.cpp
This pull request fixes #527 with the following corrections:
- When saving a scene, `UBSvgSubsetAdaptor` used `boundingRect()` to get size and position of items. This bounding rectangle is however half a pixel larger in each direction as the actual item. To fix this, that half-pixel margin is subtracted from the return value of `boundingRect()` before saving.
- The `UBBoardPaletteManager` tried to resize the left and right palette by one pixel and then revert that resizing, probably to correct a problem in Qt. The code to restore the original size was however wrong, so the left and right palette shrunk by 2 pixels each time OpenBoard was started. This code is now corrected. A comment now states, that it might probably be removed.
- Additionally I commented two lines defining and setting …
> Fix bug 527: palette and tool resize

- release_scripts/linux/build.sh
After reading source, issue https://github.com/OpenBoard-org/OpenBoard/issues/98 and doc https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Ubuntu-20.04, I succed compiling a .deb on Rpi OS for the french eductative distribution https://primtux.fr/
On Rpi 4, I had to force architecture name and QT_PATH.
> change  and QT_PATH on arm

- src/domain/UBGraphicsScene.cpp
- when using the pen tool on a ruler the "normal" cursor was shown
- instead the special drawRulerLine cursor should be shown
- UBGraphicsScene::drawPenCircle update cursor only with no active ruler
see also https://github.com/letsfindaway/OpenBoard/issues/66
> fix: cursor shown on a ruler using pen tool

- src/pdf/XPDFRenderer.cpp
- src/pdf/pdf.pri
Fix similar to the change done in inkscape, as referenced in #571. Also added flag to use c++17 compliance for compiling src/pdf as needed by poppler >= 22.01.
Closes #571, #560
> fix: compile with poppler >= 22.01

- resources/etc/OpenBoard.config
- src/adaptors/UBExportPDF.cpp
- src/core/UBSettings.cpp
- src/core/UBSettings.h
Some users suggested to add options to export the background grid and/or color to PDF. This pull request adds these features.
They can be enabled by the following configuration variables:
```
[PDF]
ExportBackgroundGrid=true
ExportBackgroundColor=true
```
Both variables are set to `false` by default, which is also the current behavior.
This feature is mentioned in
- https://github.com/OpenBoard-org/OpenBoard/issues/403
- https://github.com/OpenBoard-org/OpenBoard/issues/357
- https://github.com/OpenBoard-org/OpenBoard/issues/315
- https://github.com/OpenBoard-org/OpenBoard/issues/118
With this PR these options are only available via the configuration file. It is for further discussion if and possibly where they should also be added to the settings page of the user interface.
> Feature: Export background grid/color to PDF

- resources/etc/OpenBoard.config
- src/board/UBBoardView.cpp
- src/core/UBSettings.cpp
- src/core/UBSettings.h
This PR adds handling of the mouse wheel to zoom and scroll in a page as follows:
- If no modifier button is pressed, then the mouse wheel scrolls vertically
- If a widget with scrollable content is selected and the mouse cursor is within that widget (e.g. a captured web page), then the content of that widget is scrolled.
- If no widget is selected or the mouse cursor is outside of that widget, then the page is scrolled.
- If the `Alt` button is pressed, then the mouse wheel scrolls horizontally.
- If the `Ctrl` button is pressed, then the mouse wheel zooms in and out.
There is a new `ZoomBase` configuration value for the base of the exponential function computing the zoom factor from the wheel angle. This can be adjusted to create finer or more coarse zooming and should always be close …
> feat: mouse wheel zoom and scroll

- src/board/UBBoardView.cpp
- src/board/UBDrawingController.cpp
- src/board/UBDrawingController.h
- src/domain/UBGraphicsScene.cpp
- src/tools/UBGraphicsRuler.cpp
- src/tools/UBGraphicsTriangle.cpp
This pull request fixes #628.
Indeed there were two problems: a more obvious one and a hidden one, which also existed in previous versions.
The obvious problem:
The `UBDrawingController::mActiveRuler` variable is used to indicate an active ruler. It is set when the pointer enters the area of the ruler **with an active drawing tool** and reset when it leaves the area of the ruler. The problem was, that the bold condition was not observed for the ruler. It was however correct for the triangle. So when closing the ruler, you were actually entering the area to move to the close button. `mActiveRuler` was set and stayed effective, as the cursor could never "leave" the area of a no longer visible ruler.
The hidden problem:
Even with 1.6.1 or probably earlier versions you could provoke this …
> fix bug 628: ruler effective after removal

- src/adaptors/UBExportFullPDF.cpp
This PR tries to fix a scaling issue during PDF export using the PDF merger, where the overlay and the base PDF document where not correctly aligned. See https://github.com/letsfindaway/OpenBoard/issues/93 for an analysis of this problem.
I tested the patch also for cases where the annotations cover areas outside of the PDF document size. In these cases the PDF document and the annotations are scaled, so that everything fits on the page. Still the annotations are at the correct place.
> fix: scaling of background PDF during export

- src/adaptors/UBExportFullPDF.cpp
The feature to export background color and grid to PDF files was not enabled with `UBExportFullPDF`.
This merge requests enables drawing the background according to the corresponding configuration variables also in this case.
See also https://github.com/OpenBoard-org/OpenBoard/pull/465#issuecomment-1161309848.
> fix: restore PDF background export

- src/domain/UBGraphicsTextItemDelegate.cpp
- src/frameworks/UBStringUtils.cpp
- src/frameworks/UBStringUtils.h
- src/gui/UBResources.cpp
This patch fixes issues with font selection for the text tool:
- Huge performance improvement when building the fonts list by
- removing fonts from the models in chunks instead individually. This is important, as removing a single item from the model using `removeRow` takes nearly the same time as removing many items using `removeRows`. On my system with about 750 system fonts installed this reduced the time needed to build the fonts list from about 30 seconds to some 100 ms,
- removing duplicates from the custom fonts list. This speeds-up comparison.
- Prefix matching to find all fonts.
- The custom font list contains a prefix only, e.g. "Ecriture A", while the `dialogFontNames` contain e.g. "Ecriture A", "Ecriture A Ligne", "Ecriture A Orne" and "Ecriture A Orne Ligne". The check for …
> Fix font handling

- src/adaptors/UBSvgSubsetAdaptor.cpp
- boundingRect only adds a margin if
- it is a QAbstractGraphicsShapeItem, and
- it has a pen (style != Qt::NoPen)
- the margin is then half the pen width at each side
> fix: correct calculation of graphics item margins

- src/core/UBApplication.cpp
- src/core/UBApplication.h
This PR fixes the "known issue" and allows to double-click on an ubz file while OpenBoard is running. It will
- send a message with file name from the secondary instance and exit,
- handle message in primary instance and open the file.
This was already partly implemented, just the open ends have to be glued together to make this working.
> feat: open ubz file in running instance

- src/board/UBBoardController.cpp
- src/board/UBBoardView.cpp
- src/core/UBApplicationController.cpp
- src/core/UBApplicationController.h
- src/core/UBDisplayManager.cpp
- src/core/UBDisplayManager.h
- src/core/UBPersistenceWorker.cpp
- src/core/UBPreferencesController.cpp
- src/core/UBPreferencesController.h
- src/core/UBSettings.cpp
- src/core/UBSettings.h
- src/frameworks/UBPlatformUtils_linux.cpp
- src/frameworks/UBPlatformUtils_mac.mm
- src/frameworks/UBPlatformUtils_win.cpp
- src/frameworks/UBStringUtils.cpp
- src/frameworks/UBStringUtils.h
- src/gui/UBDockPalette.cpp
- src/gui/UBDockPalette.h
This pull request continues work on the `UBDisplayManager` and related classes. I want to thank all discussion partners and testers for their input and hope that most of them found its way to this PR.
The most noticeable improvement is the screen configuration by index instead of name. Names are too platform specific and volatile, so a simple index is the better choice. But much more has changed. Here a list in the order as the files appear below:
- The background grid size is calculated when the display manager has defined the roles of the screens.
- The boxing in window mode is calculated as if the control screen would be full screen.
- Boxing is recalculated when the window is resized.
Wheel events on "Previous" screens are no longer handled.
- The initialization and adjustment of …
> Improve displaymanager

- src/gui/UBThumbnailWidget.cpp
- src/gui/UBThumbnailWidget.h
I now tried to find a way to keep compatibility for a broader range of Qt versions. The only affected class is `UBThumbnailWidget`.
- Make `UBThumbnailWidget` compatible with Qt 5.12 upwards.
- Use a `QList` for member variable `mSelectedThumbnailItems`. This does not affect performance, as it is only used for iterating.
- Convert `QSet` to `QList` using `values()`. This function is not deprecated even in Qt 6.3.
@JBBgameich : do you think this is an appropriate approach?
> refactor: maintain compatibility with Qt 5.12

- src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp
- src/podcast/ffmpeg/UBFFmpegVideoEncoder.h
This pull request adapts the `UBFFmpegVideoEncoder` to be compatible with ffmpeg-4 as well as ffmpeg-5. The main change is that the codec context is no longer available via the `AVStream->codec`, but is kept in a separate `AVCodecParameters` structure.
Some pointers for ffmpeg versions and documentation can be found at https://github.com/letsfindaway/OpenBoard/issues/84. Most of my changes are taken from looking at the `muxing` examples for the different versions.
Finally the changes will:
- keep separate reference to AVCodecContext
- copy parameters to AVCodecParameters
- use new API in writeFrame
- use AVChannelLayout
Merging this PR should resolve #561.
> Make UBFFmpegVideoEncoder compatible with ffmpeg-5

- OpenBoard.pro
- src/core/UBSettings.cpp
- src/frameworks/UBPlatformUtils.h
- src/frameworks/UBPlatformUtils_linux.cpp
- src/frameworks/UBPlatformUtils_mac.mm
- src/frameworks/UBPlatformUtils_win.cpp
This PR improves the handling of the `onboard` on-screen keyboard on Linux. It improves the detection of the availability of the `onboard` system on-screen keyboard. Additionally it uses now `DBus` to show and hide the keyboard instead of starting and killing the application. 
- add detection function in `UBPlatformUtils`
- on Linux check for `onboard` binary
- disable system OSK if not installed
- use `DBus` to show/hide `onboard`
> Improve on-screen keyboard handling

- resources/etc/widgets.md5sum
- resources/library/applications/GeoInfo.wgt/config.xml
- resources/library/applications/iCell.wgt/config.xml
- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/adaptors/UBWidgetUpgradeAdaptor.cpp
- src/adaptors/UBWidgetUpgradeAdaptor.h
- src/document/UBDocumentProxy.cpp
- src/document/UBDocumentProxy.h
- src/domain/UBGraphicsWidgetItem.cpp
- src/domain/UBGraphicsWidgetItem.h
- src/domain/UBGraphicsWidgetItemDelegate.cpp
This PR improves the handling of widget compatibility when upgrading from OpenBoard 1.6.x to 1.7.x.
- It adds an explicit API version marker to the `config.xml` file, which identifies widgets compatible with the asynchronous API.
- It shows a note on the screen for incompatible widgets.
- It includes the location of user installed widgets (`~/.local/share/OpenBoard/interactive content/` on Linux, similar locations on other platforms) when searching for upgraded widgets.
The version marker is already documented [in my Wiki page](https://github.com/letsfindaway/OpenBoard/wiki/Widget-API#widget-upgrade).
> Check widget compatibility

- src/board/UBBoardController.cpp
This PR fixes #670 by re-initializing thumbnails in the `UBBoardThumbnailsView` after PDF import using DnD.
The reason for this crash was that the thumbnails in the page navigator on the left side of the board have not been updated when adding a PDF document using DnD. Later on however the code assumes that it can access these thumbnails by index. The missing index cause an out-of-range assertion.
The fix simply emits the `initThumbnailsRequired()` signal after import.
> Fix crash after PDF import using DnD

- src/domain/UBGraphicsWidgetItem.cpp
- src/gui/UBToolWidget.cpp
This PR assures a transparent background for widgets.
I had situations, when the background e.g. of Horologe was light gray instead of transparent. This was not always the case and it seemed that it depends on some environmental settings. It never happened when a widget was converted to a tool.
This PR harmonizes the transparency settings for widget and tool and uses additional flags to assure transparency. See also https://github.com/letsfindaway/OpenBoard/issues/107.
- fix setting flags for transparent background
- harmonize between UBGraphicsWidgetItem and UBToolWidget
Signed-off-by: letsfindaway <me@letsfindaway.de>
> fix: assure transparent background for widgets

- src/board/UBBoardController.cpp
- src/core/UBPersistenceManager.cpp
- src/core/UBPersistenceManager.h
- src/document/UBDocumentProxy.cpp
- src/document/UBDocumentProxy.h
This PR addresses #671 with the following changes:
- It removes the `shouldLoadFileData` check in `UBBoardController` and never copies dropped files here, because in all cases (audio, video, images, widget, pdf) the files are copied anyway later.
- It adds a `UBPersistenceManager::cleanupDocument` function which removes unreferenced files from the document.
> Duplicate files

- src/domain/UBWebEngineView.cpp
- src/domain/UBWebEngineView.h
- links with target=_blank cannot open a new tab from a widget
- intercept such requests and open link in same view
See also https://github.com/letsfindaway/OpenBoard/issues/115
Verified with Qt 5.15 and Qt 6.2
> feat: open target=_blank links in widgets in same view

- resources/forms/mainWindow.ui
- src/board/UBBoardController.cpp
The code currently contains some special handling for data coming from `edumedia-sciences.com` and containing Flash animations. Edumedia completely switched to HTML5, so the import feature for Flash based animations from Edumedia is obsolete. This PR removes the related code from `UBBoardController` and an already unused and unreferenced action from `mainWindow.ui`. 
Note that documents containing Flash animations imported earlier are not affected.
Note also that Edumedia content can now easily be imported to OpenBoard by using the Web content embedding feature of OpenBoard.
Third note: The translation files stillcontain text strings referring to Edumedia, but I think those should be cleaned up at some later time using 
```sh
lupdate -no-obsolete
```
> refactor: remove obsolete edumedia handling

- src/domain/UBGraphicsWidgetItem.cpp
- src/domain/UBGraphicsWidgetItem.h
See [QTBUG-108284](https://bugreports.qt.io/browse/QTBUG-108284)
- CSS styled cursors don't work with Qt 5.15 - 6.4 (at least)
- intercept CursorChange event on QWebEngineView's window
- forward to QGraphicsProxyWidget
- additionally mark other overriding functions as `override`
- commit may be reverted when bug is fixed in Qt
Fix was verified with Qt 5.15 and Qt 6.2 on Linux.
> workaround: avoid QTBUG-108284 with CSS styled cursors

- src/board/UBBoardPaletteManager.cpp
- src/board/UBBoardPaletteManager.h
- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/gui/UBBoardThumbnailsView.cpp
- src/gui/UBBoardThumbnailsView.h
- src/gui/UBFeaturesWidget.cpp
- src/gui/UBThumbnailWidget.cpp
- src/gui/UBThumbnailWidget.h
This PR provides an alternative implementation of live thumbnails for board navigation avoiding an issue with drop-down menus on web widgets. See https://github.com/letsfindaway/OpenBoard/issues/118 for a detailed discussion of this topic.
Please check this PR on a HiDPI display before merging. I assume it is ok, but this should be verified.
> Live thumbnails using QGraphicsPixmapItem

- .gitignore
- src/board/UBBoardController.cpp
- src/board/UBBoardController.h
- src/core/UB.h
- src/core/UBDownloadManager.cpp
- src/core/UBDownloadManager.h
- src/domain/UBGraphicsScene.h
- src/frameworks/UBFileSystemUtils.cpp
- src/web/UBEmbedController.cpp
- src/web/UBEmbedController.h
- src/web/UBEmbedParser.cpp
- src/web/UBEmbedParser.h
- src/web/UBWebController.cpp
- src/web/UBWebController.h
On the way to handling URLs pointing to web pages (content type is `text/html`) this PR also provides some fixes and refactoring as well as class documentation. It contains four commits:
After pasting a URL to an inaccessible URL to the board, e.g. one which returns a 404 error, any operations involving dragging on the board have been blocked due to inappropriate handling of the error case. The first commit fixes this issue.
The `QEmbedController`  and `QEmbedParser` had references to `QWebEngineView`. Architecturally this is not necessary. All these classes should do is to parse a piece of HTML and extract embeddable content, to control the embed dialog and to create the widgets.
This refactoring therefore moves these dependencies out of those classes. 
Additionally it adds some style …
> Handle paste or drop of web page URL to board

- src/adaptors/UBCFFSubsetAdaptor.cpp
- src/board/UBBoardView.cpp
- src/core/UBApplication.cpp
- src/core/UBOpenSankoreImporter.cpp
- src/document/UBDocumentController.cpp
- src/gui/UBBoardThumbnailsView.cpp
- src/gui/UBDocumentThumbnailWidget.cpp
- src/gui/UBFeaturesActionBar.cpp
- src/gui/UBFeaturesWidget.cpp
- src/gui/UBFloatingPalette.cpp
- src/gui/UBMagnifer.cpp
- src/gui/UBMousePressFilter.cpp
- src/web/simplebrowser/tabwidget.cpp
This PR fixes the deprecation warnings when compiling with Qt 5.15 or Qt 6.2.
Additionally it fixes a warning about an unused result in `UBApplication`, which should actually be used and is also easy to use.
Also a bug was fixed in the `UBMousePressFilter`, where a `QEvent` was casted to a `QTabletEvent`, even if it was in fact a `QMouseEvent`.
> Avoid deprecations for Qt 5.15 and Qt 6.2

- src/adaptors/UBSvgSubsetAdaptor.cpp
This PR fixes two memory leaks in `UBSvgSubsetAdaptor`. 
- In `UBSvgSubsetWriter::strokeToSvgPolygon` a temporary object is never deleted.
- In `UBSvgSubsetReader::pixmapItemFromSvg` an object would not be freed in an error case.
Additionally it avoids several potential `nullptr` dereferences by moving the affected code in a guarding `if`. A third commit removes two lines of code where a `QString` is constructed which is never used later.
> Fix memory leak in UBSvgSubsetAdaptor

- src/core/UBDisplayManager.cpp
- src/core/UBPreferencesController.cpp
During screen selection, change the cursor shape over the screen selection buttons.
Additionally this PR fixes some issues with screen selection which occur only in debug mode.
The second commit improves positioning of the control screen during screen configuration: There are cases when resetting the geometry does not help and `showNormal()` is still required.
> Hover over screen selection buttons

- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/domain/UBGraphicsWidgetItem.cpp
- src/domain/UBGraphicsWidgetItem.h
This PR tries to mitigate [QTBUG-109068](https://bugreports.qt.io/browse/QTBUG-109068) at least partially. It forwards the widget position to the `QWebEngineView` when
- the widget is moved,
- the viewport is changed using the hand tool, the arrow keys or  the mouse wheel.
It does not mitigate the problem with drop down menus when zooming, as there is no known workaround for this.
Changes involve:
- Inform widgets about viewport changes.
- Move workaround to common `updatePosition()` function.
> workaround: position of drop down menu in widgets

- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/adaptors/UBSvgSubsetAdaptor.h
- src/core/UBDisplayManager.cpp
- src/domain/UBGraphicsScene.cpp
This PR fixes three independent, but small issues, so I collected them into a single PR. Please let me know if you prefer individual PRs for each of them. The fixes are:
- Fix for #597 which blocked OpenBoard when opening a document with irregular z values.
- Fix for an issue where the palette size was reduced when OpenBoard was started and the palettes are visible. Resize events are now suppressed during repositioning of screens to avoid this.
- Fix for #710 as proposed in my comment on this issue. Changing the page size now sets the document as "modified" and refreshes the cache.
> Multiple fixes: irregular z values, palette size, save page size

- src/board/UBBoardView.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
This PR harmonized the drawing of the background in the scene and the view, which is currently duplicated with mostly identical code. It does:
- move all drawing of background grid to UBGraphicsScene
- only add document border in UBBoardView
- avoid some compiler warnings
This PR should be merged before enabling the intermediate background grid lines by default, as currently the intermediate lines are not drawn in the magnifier tool due to an inconsistency in the two implementations.
See also discussion at https://github.com/letsfindaway/OpenBoard/issues/12
> refactor: drawBackground mostly in scene

- src/adaptors/UBExportFullPDF.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/pdf/GraphicsPDFItem.h
- src/pdf/PDFRenderer.h
- src/pdf/XPDFRenderer.cpp
- src/pdf/XPDFRenderer.h
This PR clarifies the way how the page size is calculated when a page has a background PDF. It uses the floating point variants for size and rect and removes rounding to make the calculations accurate and to avoid small offsets.
- add functions to retrieve original PDF page size in Points
- make output pages the same size
- align page sizes between overlay and base PDF
- use QSizeF where necessary to improve accuracy
- compute sceneBoundingRect only once
- catch exception by const reference (best practice)
> fix: size of exported PDF page

- src/frameworks/UBPlatformUtils.h
- src/frameworks/UBPlatformUtils_linux.cpp
The visibility state of the `onboard` keyboard could be changed by means external to OpenBoard, e.g. by simply hiding the keyboard with the :x: key in the upper right corner. Currently OpenBoard cannot detect such changes. In order to make the `onboard` keyboard visible again, the user would have to tap the OpenBoard action twice.
In order to keep states synchronized, this PR
- adds the `OnboardListener` class to listen for visibility changes, and
- triggers (and thus synchronizes) the corresponding action when visibility was changed externally.
This also invokes any other tasks (e.g. update mask in desktop mode) connected to a change in keyboard visibility.
> fix: sync onboard state with internal action

- src/adaptors/UBImportImage.cpp
- src/adaptors/UBImportImage.h
- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/board/UBBoardController.cpp
- src/board/UBBoardPaletteManager.cpp
- src/board/UBFeaturesController.cpp
- src/board/UBFeaturesController.h
- src/core/UBPersistenceManager.cpp
- src/domain/UBGraphicsPixmapItem.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/gui/UBFeaturesWidget.cpp
- src/gui/UBFeaturesWidget.h
This PR addresses the storage consumption of OpenBoard documents containing images. 
Currently, all images are converted to PNG and stored as such. So JPEG images with a reasonable large resolution end up using much disk space.
This PR
- avoids conversion of any image to PNG, as it needs a lot of disk space,
- stores imported or dropped image files as their original data in the OpenBoard document,
- while OpenBoard versions before 1.7.0 can still read the documents.
The core change is a new function `addImage` in `UBGraphicsScene`, which shall replace `addPixmap` in as many cases as possible. Instead of a pixmap, it takes a `QByteArray` of the image data. All other parameters are the same. The data is stored to disk as is.
The code for importing an image, for reading and writing a …
> perf: store images in source format

- src/adaptors/UBExportFullPDF.cpp
- src/domain/UBGraphicsScene.cpp
I hope this PR now finally fixes the PDF export scaling. The main changes are
- use pageDpi to convert scene units to PDF units
- take the scaling between original PDF and scene into account
- use actual appearance on scene to calculate the scaling factor
- avoid rounding error in UBGraphicsScene::normalizedSceneRect
In fact this reintroduces a former idea, but in a different implementation. originally, the scaling of a PDF document on the scene was computed by getting `m11` of the transformation matrix. There were however cases - and I cannot exactly tell why - when this was not what we see on the screen. Now this factor is computed by using the scene bounding rect of the PDF and its original size as taken from the document.
When interpreting the scene coordinates, we now always use the …
> fix: PDF export when background PDF was scaled

- src/adaptors/UBExportDocumentSetAdaptor.cpp
- src/adaptors/UBImportCFF.cpp
- src/api/UBWidgetUniboardAPI.cpp
- src/api/UBWidgetUniboardAPI.h
- src/core/UBPersistenceManager.cpp
- src/document/UBDocumentController.cpp
- src/document/UBDocumentProxy.cpp
- src/document/UBDocumentProxy.h
This PR fixes two issues in `shared_ptr` handling:
- It avoids copying the `UBDocumentProxy` objects during construction via `make_shared`.
- It breaks a circular reference between web widgets and scene.
See also https://github.com/letsfindaway/OpenBoard/issues/132
The first commit fixes the calls to `make_shared`. It also makes the `UBDocumentProxy` uncopyable and unassignable to prevent such things to happen inadvertently.
The second commit uses a `weak_ptr` to the scene in the `UBWidgetUniboardAPI` to break the circular reference.
> Fix shared ptr

- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/core/UBApplicationController.cpp
- src/core/UBPersistenceManager.cpp
- src/core/UBPersistenceManager.h
- src/core/UBPersistenceWorker.cpp
- src/core/UBPersistenceWorker.h
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/domain/UBGraphicsStroke.cpp
- src/domain/UBGraphicsStroke.h
- src/domain/UBGraphicsWidgetItem.cpp
- src/domain/UBGraphicsWidgetItem.h
- src/podcast/UBPodcastController.cpp
- src/tools/UBGraphicsCache.cpp
- src/tools/UBGraphicsCache.h
Another PR to stabilize the usage of `shared_ptr`:
- break `shared_ptr` cycles in `UBGraphicsStroke`
- break `shared_ptr` cycles in `UBGraphicsCache`
- maintain ownership of `UBGraphicsCache` in `UBGraphicsScene`
- do not pass `shared_ptr` to other threads (`UBPersistenceWorker`)
- better handling of scene for `UBWidgetUniboardAPI`
- release scene after encoding in `UBPodcastController`
A detailed description is available here: https://github.com/letsfindaway/OpenBoard/issues/132#issuecomment-1553012031
> fix: shared_ptr in threads, circular references, others

- plugins/cffadaptor/src/UBCFFAdaptor.cpp
- plugins/cffadaptor/src/UBCFFConstants.h
- src/adaptors/UBCFFSubsetAdaptor.cpp
- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/board/UBBoardController.cpp
- src/core/UB.h
- src/core/UBForeignObjectsHandler.cpp
- src/core/UBPersistenceManager.cpp
- src/core/UBPreferencesController.cpp
- src/document/UBDocumentController.cpp
- src/gui/UBDockPalette.cpp
- src/gui/UBDockPalette.h
- src/gui/UBFloatingPalette.cpp
- src/gui/UBFloatingPalette.h
- src/gui/UBKeyboardPalette.cpp
- src/gui/UBKeyboardPalette.h
- src/gui/UBToolWidget.cpp
- src/gui/UBToolWidget.h
- src/network/UBHttpGet.cpp
Unfortunately I have broken Qt6 compatibility with two commits:
- 27ae0146f9407004e9b4c720e0ddc5b94d0c9bfa introduced the `leftRef` calls. These are not necessary and do no longer exist in Qt6.
- 7ba86ecdbece5b88770d614f2a3254c2b236d183 added an `enterEvent`, which has a different parameter type in Qt6. Due to the `override` annotation this was flagged as a compile error. I found some more occurrences of that problem which have not been flagged as a compile error because of the missing `override` annotation.
This PR fixes these issues, which only occur when compiling with Qt6.
- use `QString::left`, `mid` instead of `leftRef`, `midRef` as `QStringRef` is obsolete in Qt6
- use modified signature of `enterEvent`, parameter type is now `QEnterEvent*` instead of `QEvent*`
> Fix broken Qt6 compatibility

- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/web/UBEmbedController.cpp
This PR fixes two issues:
- #774 
- https://github.com/letsfindaway/OpenBoard/issues/134
The first issue was caused by a missing `keyReleaseEvent` for the `Ctrl` key when pasting a URL via `Ctrl-V`. This caused that the `UBBoardView` was still in multi-selection mode and mouse events were not forwarded to the widget or its delegate.
The first commit fixes this issue. The state of the `Ctrl` key is now determined from the `QMouseEvent::modifiers()` instead from key events. This solution is robust against missing key events and is most probably what you want.
The second issue could occur when creating a widget from a web page with a very long title or a title with some special characters or HTML entities, as the title is used as folder name for the newly created widget. In this case, either …
> Fix frozen objects and illegal widget file name

- resources/startupHints/locales/de/1.html
- resources/startupHints/locales/de/10.html
- resources/startupHints/locales/de/11.html
- resources/startupHints/locales/de/12.html
- resources/startupHints/locales/de/2.html
- resources/startupHints/locales/de/3.html
- resources/startupHints/locales/de/4.html
- resources/startupHints/locales/de/5.html
- resources/startupHints/locales/de/6.html
- resources/startupHints/locales/de/7.html
- resources/startupHints/locales/de/8.html
- resources/startupHints/locales/de/9.html
- resources/startupHints/locales/de/error.html
- harmonize name of modes: Board, Dokumente, Desktop, Internet
- correct some sentence structure
- add missing icon references
- translate the error page
> fix: update German translation of hints and tips

- src/domain/UBGraphicsWidgetItem.cpp
- src/domain/UBGraphicsWidgetItem.h
This PR proposes some improvements and refactorings for the handling of accented characters in web widgets
- make lookup maps `const static` instead of creating them for each instance of a web widget
- initialize `mLastDeadKey` in header file
- avoids additional ifdef in the code
- handle two dead keys in a row
- same key: write accent
- different keys: drop both
- suppress blank after dead key
- use local variable for generated events to free memory afterwards
- allocate an event if you send it via `QApplication::sendEvent`
- but keep ownership if you pass it directly to an event handler
- fix key parameter when constructing `currentDeadKeyEvent`
- compact code by squashing consecutive `if` statements
- use `const` wherever possible
- use conversion `QString(const char*)` instead of …
> refactor: handle accented characters in web widgets

- src/gui/UBThumbnailWidget.cpp
- always perform full update if tool is Play or Selector
- these tools may cause modifications outside of the visible area
see also https://github.com/letsfindaway/OpenBoard/issues/143
> fix: update region for live thumbnails

- src/gui/UBThumbnailWidget.cpp
- src/gui/UBThumbnailWidget.h
I think I finally found a solution for the problem with glitches when moving items below a live thumbnail, especially in large zoom factors. See https://github.com/letsfindaway/OpenBoard/issues/143#issuecomment-1771092503. We have to
- disable updates of board while updating thumbnail, and
- ignore the next repaint event on the board induced by re-enabling updates for thumbnail update.
> Fix glitches when moving items below live thumbnails

- src/core/UBApplicationController.cpp
- src/domain/UBWebEngineView.cpp
- src/tools/UBGraphicsAxes.cpp
- src/web/UBWebController.cpp
- src/web/simplebrowser/browserwindow.cpp
- src/web/simplebrowser/downloadwidget.cpp
- src/web/simplebrowser/tabwidget.cpp
- src/web/simplebrowser/webpage.cpp
- src/web/simplebrowser/webpopupwindow.cpp
- src/web/simplebrowser/webview.cpp
During my tests for the issue with the live thumbnails I got some sporadic crashes while zooming. I now could catch two occurrences and I think I can trace them back to dangling connections pointing to deleted objects. See https://github.com/letsfindaway/OpenBoard/issues/147.
Here is my fix:
- connections to a lambda are only automatically deleted if
- the sender is deleted or
- a context parameter is given in the connect call before the lambda
- use `clazy` to find all missing context parameters
- add missing context parameter to lambda connections
- note: not all fixed lines are "dangerous"
- as many fulfill the first condition
- they are deleted when the sender is deleted
> fix: sporadic crash due to dangling connection

- src/gui/UBStartupHintsPalette.cpp
When opening the startup hints using the OpenBoard menu, the checkbox "Visible next time" is always checked. Instead I would expect that it represents the current status of the `EnableStartupHints` setting.
This simple PR sets the checked state of the startup hints visibility checkbox according to the `EnableStartupHints` setting.
I have based my branch on `master`, so that it can be applied to either `dev` or `1.7.1-dev`.
> fix: initial state of startup hints visibility checkbox

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/build-problem.md
- .github/ISSUE_TEMPLATE/feature_request.md
In order to encourage contributors to write good bug reports and useful feature requests I propose to add a set of issue templates to the project. 
These issue templates are based on the default proposals of GitHub and adapted to the needs of OpenBoard. See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates for a description of issue templates in GitHub.
> Add issue templates

- src/adaptors/UBMetadataDcSubsetAdaptor.cpp
This PR fixes a minor bug where OpenBoard crashes on startup when trying to parse a document with an invalid document size. This should normally not happen, but such a document could be a leftover from another crash. See https://github.com/letsfindaway/OpenBoard/issues/129 for more details.
This PR fixes that issue. When opening a document with invalid document size, it avoids using the display manager, but uses the default document size from the settings instead.
> fix: avoid access to uninitialized DisplayManager

- src/domain/UBGraphicsScene.cpp
This PR fixes a minor issue with the eraser. Sometimes it does not work when the eraser is completely inside a polygon, e.g. a very small eraser outline in a broad marker stroke. See https://github.com/letsfindaway/OpenBoard/issues/153 for a complete description and analysis.
This PR fixes this by reversing the `eraserPath` to have opposite orientation of the stroke. This is necessary for punching a hole with the `WindingFill` rule.
> fix: eraser not working when completely inside polygon

- src/tools/UBAbstractDrawRuler.cpp
- src/tools/UBGraphicsRuler.cpp
- src/tools/UBGraphicsRuler.h
The ruler background was a normal rectangle compared to the rounded border. The background is now rounded too and the outline that is used for the border is also used for the background, so they are now directly linked.
Fixed the points under `Ruler` in #828. The ruler button layout now looks consistent with non-overlapping elements even at high or low zoom levels.
> Improve Ruler widget and buttons

- resources/forms/mainWindow.ui
- src/board/UBBoardView.cpp
- src/domain/UBGraphicsTextItem.cpp
- src/domain/UBGraphicsTextItem.h
My usecase is : 
I used to change the format of the text. For example, some words in bold or italic or underlined. And I want to go fast without opening the font dialog.
The idea is to implement the reception of events in the `UBGraphicsTextItem`. And we do the text modification if the event is a `bold` or `italic` or `underline` shortcut. 
I do not know if it will be better to do it in `UBGraphicsTextItemDelegate`.
It works fine in my side on linux and Qt 5 and 6.
The only issue is due to other `Ctrl+I` shortcut to set the stylus. The `italic` shortcut set the text in italic but also switches in stylus mode and the Text box loses the focus.
> New bold, italic and underline shortcuts for text box.

- CMakeLists.txt
Poppler uses [`std::string::starts_with`](https://en.cppreference.com/w/cpp/string/basic_string/starts_with) since [poppler/poppler@fbb645](https://gitlab.freedesktop.org/poppler/poppler/-/commit/fbb64544e5ea25ac9b1bd25b48043d074efe9cd9). This commit (fbb645) is included in `poppler 24.05`. This change also affects the public headers of GooString, which means that all projects depending on `poppler` need to be aware of `std::string::starts_with`, even if they don't use it themselves.
`std::string::starts_with` is new with C++ 20 (see above), which means that OpenBoard must also be compiled with C++ 20. Otherwise, this error occurs:
```
/usr/include/poppler/goo/GooString.h:241:24: error: ‘starts_with’ has not been declared in ‘std::string’
241 |     using std::string::starts_with;
| …
```
> fix: Enable use of C++20 for compatibility with poppler 24.05

- README.md
- src/board/UBBoardController.cpp
When for example an image is pasted into the current document, it always lands in the center of it, regardless of where the user's view is located. This might be unintuitive for some users, who would expect the newly-pasted image to pop up on their screen, regardless of which part of the document they are looking at, and not have to scroll back to the document's center. This pull request fixes this issue.
> Paste in the middle of current view, not in the center

- src/board/UBBoardController.cpp
- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/core/UBApplicationController.cpp
- src/core/UBDisplayManager.h
This PR fixes the display view scaling issue reported in #887 as follows:
- scaling shall be based on control view size instead of page size
- scaling has to take into account the system scale factor
- refactor: use `center()` function of `QRect` instead of own calculation
The problem (and also the resolution using this PR) can be verified in a setup where control and display screen have different aspect ratios.
> fix: scaling of display view

- src/frameworks/UBFileSystemUtils.cpp
- src/frameworks/UBFileSystemUtils.h
The functions `MD5_Init`, `MD5_Update`, `MD5_Final` are deprecated in OpenSSL 3.0. This leads to warnings during compilation.
~~Use `EVP_Q_digest` instead.~~
**Edit:** Since the utility functions `md5` and `md5InHex` are not used anywhere, just remove them.
> Remove MD5 hashing from UBFileSystemUtils

- resources/library/interactivities/Dice.wgt/config.xml
- resources/library/interactivities/Dice.wgt/css/ubw-main.css
- resources/library/interactivities/Dice.wgt/js/lib/ubw-main.js
- src/adaptors/UBWidgetUpgradeAdaptor.cpp
When updating the interactivity widgets to the new OpenBoard API, the `Dice` widget was forgotten. This PR fixes this in two commits:
- The first commit extends the `UBWidgetUpgradeAdaptor`. It was initially written to upgrade widgets which have been using the old API to updated versions using the new API. The extension added now can also update a widget already using the new API to a new version.
- The second commit applies all the changes necessary for `uwb-main` based widgets.
The automatic version update makes sure that widgets on already existing documents get automatically updated. The update is performed if
- The widget existing in the document has a valid ID and version number.
- The widget existing in the document does not use the old API. Using the old API takes us to the …
> Fix Dice widget and add automatic update

- src/podcast/ffmpeg/UBFFmpegVideoEncoder.cpp
With FFmpeg 7.0 entering [Arch Linux extra-testing](https://archlinux.org/packages/extra-testing/x86_64/ffmpeg/), it's a good time to get support for it in OpenBoard.
This PR fixes the compilation errors and resolves related warnings.
The proposed alternatives are available since 5.1 at least, so the pragmas could be lowered to get rid of warnings in previous versions - I've elected to keep the change as small as possible, so the fix only applies to version 7.0.
I'd like to have this commit merged before Arch upgrades FFmpeg to general availability, though I don't have a timeline for when that will happen. A new release of OpenBoard is not necessary.
Fixes #1002
> Support FFmpeg 7.0

- src/core/UBApplication.h
- avoid to static_cast UBApplication object while constructor is still not completed
- fixes problem to determine userDirectory before ApplicationName and OrganizationName are defined
This PR fixes some strange problems we recently had with OpenBoard using the wrong user data directory. Especially it helps (or even solves?) the problems described in
- #1004 
- https://github.com/OpenBoard-org/OpenBoard/issues/951#issuecomment-2139682397
> fix: cast for UBApplication object during construction

- src/core/UBDisplayManager.h
When
- more than one monitor is connected,
- no monitor or more than one monitor is configured in the preferences,
- and single monitor mode was selected in the OpenBoard menu,
then the control display was still boxed as if the display screen (projector) was used.
This PR fixes the values returned by `hasDisplay()` and `hasPrevious()` in the `UBDisplayManager` to include the value of the multi-monitor flag.
Related issues:
- #887
- #943
Note: This is not the same problem as addressed by #901. In that PR it is about scaling of control and display view in multi-monitor mode. This PR fixes a problem in single-monitor mode.
> fix: boxing in singlescreen mode

- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/domain/UBGraphicsScene.cpp
When exporting a document containing axes to PDF, the axes are not exported. They are currently treated as a tool like the ruler or compass, which do not belong to the page content. However he axes are different. They are an integral part of the page content and should be exported.
This PR avoids registering axes as a tool when creating them and when loading a document page containing axes.
This PR is related to #924. It only addresses the axes tool, where it is evident that it is part of the page content. For other tools like ruler, protractor or triangle it can still be discussed whether they should be part of the PDF export.
> fix: export axes to PDF

- src/gui/UBScreenMirror.cpp
fix: do not scale the already scaled pixmap when drawing in UBScreenMirror
> fix: scaling of mirror pixmap

- plugins/cffadaptor/src/UBCFFAdaptor.cpp
- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/adaptors/UBWidgetUpgradeAdaptor.cpp
- src/api/UBWidgetUniboardAPI.cpp
- src/board/UBBoardPaletteManager.cpp
- src/board/UBBoardView.cpp
- src/board/UBFeaturesController.cpp
- src/core/UBApplication.cpp
- src/core/UBDisplayManager.cpp
- src/core/UBPersistenceManager.cpp
- src/core/UBPreferencesController.cpp
- src/core/UBSetting.cpp
- src/document/UBDocumentController.cpp
- src/gui/UBBoardThumbnailsView.cpp
- src/gui/UBDockPalette.cpp
- src/gui/UBMousePressFilter.cpp
- src/gui/UBToolbarButtonGroup.cpp
- src/pdf-merger/Object.cpp
- src/pdf-merger/Parser.cpp
- src/pdf-merger/Utils.cpp
- src/podcast/UBPodcastRecordingPalette.cpp
- src/web/UBEmbedParser.cpp
- src/web/UBWebController.cpp
Similar warnings are grouped into commits. If there are questions or suggestions, you may comment below, so we can discuss them. The solutions are based on the compiler recommendations.
Where changes cannot be made cross-compatible, they are version gated (mostly concerns Qt 6 vs Qt 5).  Some warnings remain that are a bit more involved (mainly around FFmpeg and OpenSSL/MD5).
Run on Arch Linux with Qt 6.7.1 and C++20 on GCC 14.1.1.
> Fix qt and c++ warnings

- src/adaptors/UBCFFSubsetAdaptor.cpp
- src/api/UBWidgetUniboardAPI.cpp
- src/core/UBDocumentManager.cpp
- src/core/UBPersistenceManager.cpp
- src/core/UBPersistenceManager.h
- src/desktop/UBCustomCaptureWindow.cpp
- src/desktop/UBDesktopPalette.cpp
- src/document/UBDocumentController.cpp
- src/domain/UBGraphicsItemDelegate.cpp
- src/domain/UBGraphicsMediaItem.cpp
- src/domain/UBGraphicsMediaItemDelegate.cpp
- src/gui/UBThumbnailWidget.cpp
- src/gui/UBToolWidget.cpp
- src/gui/UBToolWidget.h
- src/web/UBEmbedController.cpp
- src/web/UBWebController.cpp
- src/web/simplebrowser/WBHistory.cpp
This PR avoids some `clang-tidy` and `clazy` warning messages indicating potential serious problems:
- `clang-analyzer-core.CallAndMessage`: potential call using `nullptr`
- `clang-analyzer-core.uninitialized.Branch`: potential uninitialized value in branch condition
- `clang-analyzer-core.uninitialized.UndefReturn`: potentially undefined return value
- `clang-analyzer-cplusplus.NewDelete`:potential double-free or use-after-free problem
- `clang-analyzer-cplusplus.NewDeleteLeaks`: potential memory leak
- `clazy-incorrect-emit`: incorrect or missing `emit`
It's the first part of my work on https://github.com/letsfindaway/OpenBoard/issues/148, where I try to identify and mitigate problematic code.
> Refactor: avoid serious clang warnings

- src/core/CMakeLists.txt
- src/gui/CMakeLists.txt
- source files have been removed
- remove UBOpenSankoreImporter from core/CMakeLists.txt
- remove UBOpenSankoreImporterWidget from gui/CMakeLists.txt
> chore: remove cmake files related to OpenSankore import

- src/board/UBBoardController.cpp
- in Qt5, the foreground is not correctly redrawn after calling centerOn
- it is redrawn however with translate
- combine centerOn with a small translation to workaround this problem
> fix: workaround foreground repaint after centerOn

- src/board/UBBoardController.cpp
When starting OpenBoard, there was the following warning:
```
QObject::disconnect: Unexpected nullptr parameter
```
This PR fixes this.
- fix regression introduced with 3e76f16
- check receiver before disconnecting signal
- only disconnect when receiver is not-null
> fix: disconnect with nullptr receiver

- src/adaptors/UBSvgSubsetAdaptor.cpp
- src/adaptors/UBSvgSubsetAdaptor.h
- src/core/UBPersistenceManager.cpp
- src/core/UBPersistenceManager.h
- src/core/UBPersistenceWorker.cpp
- src/core/UBPersistenceWorker.h
- src/core/UBSceneCache.cpp
- src/core/UBSceneCache.h
- src/core/main.cpp
- src/domain/UBGraphicsItemDelegate.cpp
- src/domain/UBGraphicsItemDelegate.h
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/domain/UBGraphicsStrokesGroup.h
- src/gui/UBBoardThumbnailsView.cpp
- src/gui/UBBoardThumbnailsView.h
- src/gui/UBThumbnailWidget.cpp
- src/gui/UBThumbnailWidget.h
This PR aims to improve performance of scene handling especially with documents with many pages, where each page has many items. This occurs when pages contain a lot of handwriting. Such scenes could be several megabytes as SVG and also occupy a lot of memory when loaded as scene.
Also loading of such pages takes considerable time. Since **all** pages of a document are currently loaded when the document is opened in order to assign the scenes to the board thumbnails, opening such heavy documents can currently take many seconds.
Currently the scene cache only grows. Scenes are never deleted from the cache. This can lead to memory exhaustion and crashing of OpenBoard.
The PR implements the following in three commits:
- The first commit addresses the long loading times when opening a …
> Perf lazy loading

- src/board/UBDrawingController.cpp
- src/board/UBDrawingController.h
- src/core/CMakeLists.txt
- src/core/UBApplication.cpp
- src/core/UBSettings.cpp
- src/core/UBShortcutManager.cpp
- src/core/UBShortcutManager.h
- src/core/core.pri
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/gui/UBActionPalette.cpp
- src/gui/UBActionPalette.h
- src/gui/UBBackgroundPalette.cpp
- src/gui/UBMainWindow.cpp
- src/gui/UBStylusPalette.cpp
- src/gui/UBToolbarButtonGroup.cpp
This PR is a subset of #955 with all the improvements in shortcut handling, but without the preferences dialog.
It contains all improvements described here: https://github.com/OpenBoard-org/OpenBoard/pull/955#issuecomment-2306416089. 
It also contains the option to use shortcuts without the `Ctrl` modifier by setting
```ini
[Shortcut]
IgnoreCtrl=true
```
in the configuration file. This is especially useful to activate shortcuts with a single hand.
Note that this PR already contains the full-fledged `UBShortcutManager`, which includes collecting shortcuts from various places and presenting them as a table model for a UI. This is the base for implementing a configuration dialog later, even if many of its functions are currently unused.
> Feat: improve shortcut handling

- src/gui/UBMainWindow.cpp
Addition between enums is deprecated, and in Qt6 support for the + operator between modifiers and keys gets deprecated. Instead, the | operator is provided.
The | operator is supported in both Qt5 and Qt6.
Resolves warning 4 in #1046
> refactor(UBMainWindow): Use | to combine keys

- resources/forms/intranetPodcastPublishingDialog.ui
The title for publishing to the intranet references Youtube: "Publish Podcast to YouTube". Instead use (the more generic) "Publish to Intranet".
> fix(intranetPodcastPublishingDialog.ui): Title string corrected

- src/gui/UBBoardThumbnailsView.cpp
This PR fixes a possible crash which can be reproduced with the following steps:
1. Start OpenBoard.
2. Go to document mode and open a document with a small number of pages, let's say only one.
3. Again go to document mode and open a document with more pages.
4. In this document, go to a page with a higher number than the first document's page count.
5. Open the favorites in the library palette. You see the opened documents.
6. Drag the first document to the board. everything is ok.
7. Drag the second document to the board. OpenBoard crashes.
The reason is that when dragging the second document and switching to the selected page of that document the thumbnail update is triggered, even if the thumbnails for that document have not been created.
This PR is very simple and just fixes the …
> fix: index range check for thumbnails

- resources/etc/OpenBoard.config
- src/board/UBBoardController.cpp
- src/board/UBBoardController.h
- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/core/UBSettings.cpp
- src/core/UBSettings.h
- src/domain/UBGraphicsDelegateFrame.cpp
- src/domain/UBGraphicsDelegateFrame.h
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/domain/UBSelectionFrame.cpp
- src/domain/UBSelectionFrame.h
- src/gui/CMakeLists.txt
- src/gui/UBSnapIndicator.cpp
- src/gui/UBSnapIndicator.h
- src/gui/gui.pri
- src/tools/UBGraphicsAxes.cpp
- src/tools/UBGraphicsCompass.cpp
- src/tools/UBGraphicsCompass.h
- src/tools/UBGraphicsProtractor.cpp
- src/tools/UBGraphicsProtractor.h
- src/tools/UBGraphicsRuler.cpp
- src/tools/UBGraphicsRuler.h
- src/tools/UBGraphicsTriangle.cpp
- src/tools/UBGraphicsTriangle.h
This pull request adds a snap-to-grid function when drawing lines and moving tools or objects and resizing objects. In detail it provides the following functions:
- The `Shift` key is no longer used for multi-selection. Instead now only the `Ctrl` key works for that. Before, both keys were used for multi-selection.
- The `Shift` key is now used to activate snap-to-grid. The snap function is only active while this key is pressed. If `Shift` is not pressed, all draw, move and resize operations do not snap.
- This also means that the current 0°/45°/90° snap when drawing lines is no longer active when `Shift` is not pressed. This was requested by several people who wanted to draw "near horizontal" lines.
With the `Shift` key pressed, some points snap to the grid as follows:
- If the …
> Feat: snap to grid

- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/board/UBDrawingController.cpp
- src/domain/UBGraphicsDelegateFrame.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBSelectionFrame.cpp
- src/gui/UBSnapIndicator.cpp
- src/gui/UBSnapIndicator.h
This PR addresses comment https://github.com/OpenBoard-org/OpenBoard/pull/1013#issuecomment-2360432207. The snap indicator is now shown at the point which caused the snapping. If this is outside of the visible area of the view, then the indicator is shown at the edge of the visible area.
- display snap indicator at the corner of the moved object which snapped
- limit indicator position by visible area of the view
- move appearing of the snap indicator to the snap(QRectF) function
- for rotated objects this makes it obvious that the corners of the bounding rectangle snap, not the corners of the object itself
Additionally this PR solves the problem with glitches when moving objects in a second commit.
- the already known problem with glitches when moving objects and the thumbnail palette is …
> feat: display snap indicator at the respective corner

- src/core/UBDisplayManager.cpp
This PR adds a workaround for control screen positioning with Qt 6as reported in #1080. For me this problem occurs on my system (Leap 15.6, X11)
- when compiling with Qt 6.6 or Qt 6.7
- with 2 physical monitors connected
- for the Flatpak and the distribution packages.
This PR mitigates this problem.
- Positioning and sizing of control screen does not work with Qt 6
- setGeometry() has not the desired effect
- additionally use move() and resize()
> workaround: control screen positioning with Qt 6

- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
This PR solves the issue reported here: https://github.com/OpenBoard-org/OpenBoard/pull/1013#issuecomment-2351172109
- snap-to-grid did not work for lines that also fulfill the snap-to-angle criterion
- check and compare the snap points for both criteria
- if they result in the same line angle, then the snap-to-grid criterion is preferred
> fix: snap to grid for angle-aligned lines

- src/domain/UBGraphicsMediaItem.cpp
- src/gui/UBBoardThumbnailsView.cpp
This PR fixes two crashes in two commits.
The first one is a crash occurring with Qt 6 when a scene containing a video item is deleted.
- The destructor `~UBGraphicsMediaItem()` was calling `stop()` on the `QMediaPlayer`, which is a child object of the media item. 
- This again caused the `playbackStateChanged` signal to be emitted.
- This signal was connected to `UBGraphicsVideoItem::mediaStateChanged`. `UBGraphicsVideoItem` is a class derived from `UBGraphicsMediaItem`.
- Now what happens during destruction of such a ` `UBGraphicsVideoItem`: The destructors are invoked starting from the derived class and then up to the base class.
- First `~UBGraphicsVideoItem()` is invoked. There is no destructor defined, so the default destructor is used. After that, the object looses its property of …
> Fix crash deleting scene with media item

- resources/images/stylusPalette/snap.svg
- resources/images/stylusPalette/snapOn.svg
This PR fixes #1118 and aligns the size of the new magnet icon with the other icons in the Stylus palette.
- change viewport to 42x42 px
> fix: align size of magnet icon

- resources/i18n/OpenBoard_el.ts
I updated the translation file using Qt Linguist, following @kaamui instructions in PR #987.
Is there such a way to translate the applications locales (they are in .js format) as well as html and pdf files from OpenBoard Website repository?
Also in some strings (which have singular and plural entries) I get the following warning:
"Translation does not contain the necessary %n/%ln place marker"
I translated those strings keeping the "%1" markers from the source. Should I do something else?
> Updated greek language

- src/core/UBPersistenceWorker.cpp
- src/core/UBPersistenceWorker.h
Cherry-picked from `letsfindaway/try-fix-import`
This PR fixes a sporadic crash occurring when a huge number of pages is saved, e.g. during PDF import.
- the list of saves in `UBPersistenceWorker` is accessed by more than one thread.
- protect access to the list with a mutex
> fix: crash when accessing list

- src/core/UBApplication.cpp
- src/core/UBApplication.h
- src/core/UBSceneCache.cpp
This PR provides a fix for issue https://github.com/letsfindaway/OpenBoard/issues/191.
- OpenBoard crashes when it is terminated while a scene is loading in background
- the timer used for background loading still runs and accesses resources no longer available
- add a flag `isClosing` to `UBApplication`
- check flag in timer routine in `UBSceneCache`
> fix: crash when closing while scene is loading

- src/board/UBBoardController.cpp
This PR solves a problem when dropping a PDF url to the board. Expected behavior is that the same functions are executed as when dropping a PDF document to the board. Instead in most cases just nothing happens.
- when dropping a url to the board, the data is downloaded and then processed in `UBBoardController::downloadFinished`
- for a pdf, the data is written to a temporary file and then imported
- before importing, the file must be closed to write pending data from buffers to disk
- however the file was only closed after the import, so the data was not completely written to disk
> fix: dropping pdf url to board

- src/domain/UBGraphicsMediaItem.cpp
- src/domain/UBGraphicsPDFItem.cpp
- src/domain/UBGraphicsPixmapItem.cpp
- src/domain/UBGraphicsPolygonItem.cpp
- src/domain/UBGraphicsStrokesGroup.cpp
- src/domain/UBGraphicsSvgItem.cpp
- src/domain/UBGraphicsTextItem.cpp
- src/domain/UBGraphicsWidgetItem.cpp
- src/tools/UBGraphicsCurtainItem.cpp
This PR should fix #1167
- for most items, only zValue was copied when cloning
- now also copy the ItemOwnZValue data property
Notes:
- It could also be an idea to use `UBGraphicsItem::assignZValue()` in these cases. which assigns a z value to both, the data property and the item itself. However I'm not sure whether these values could differ while cloning.
- As the z value is something common to all items, we could also extract copying of this parameter to a base class. However I did not want to introduce such a change here without discussion. There are possibly other such common parameters which should be copied for all item types.
> fix: copy ItemOwnZValue when cloning item

- README.md
- src/board/UBBoardView.cpp
- version.txt
This PR tries to fix #437. 
- use correct tool after switching to/from tablet eraser
- re-evaluate `currentTool` after changing it by the tablet eraser
However I need some testers, as I do not have a tablet with an eraser function. I will add this PR as a patch to my experimental builds, so that experimental packages are available later this day.
@bruening-bw : there will be packages for several versions of Debian available. So it would be helpful if you could test whether this fixes the issue for you.
> fix: tool usage with tablet eraser

- src/domain/UBGraphicsDelegateFrame.cpp
This PR fixes #1105:
- the handles on a delegate frame may be stacked on each other
if the delegate frame is small in one or the other direction
- determine tool from mouse position by asking the topmost
handle first
- use `isUnderCursor()` to be sure that the tool matches the
currently shown cursor
- remove unreachable `return`
> Fix delegate handle recognition

- src/board/UBBoardView.cpp
- src/board/UBBoardView.h
- src/domain/UBGraphicsDelegateFrame.cpp
- src/domain/UBGraphicsDelegateFrame.h
- src/domain/UBGraphicsScene.cpp
- src/gui/UBSnapIndicator.cpp
- src/gui/UBSnapIndicator.h
This PR applies the snap-to-grid function correctly to rotated items. It tries to make snapping more foreseeable and toi better fit user expectations for rotated items.
- When moving an arbitrarily rotated item the corners of the item snap. Snap indicators are now correctly shown at the item corners. Until now, a scene bounding rectangle of the item snapped and the snap indicators have been shown on that virtual, invisible rectangle.
- Snapping is now also correctly applied to flipped items.
- Resizing of rotated items can now also snap to the grid if the angle is 0°, 90°, 180° or 270°. For other angles it makes no sense to snap resizing.
- Scaling of an item (i.e. resizing with the bottom-right handle) never snaps.
See also https://github.com/letsfindaway/OpenBoard/issues/185 for a …
> Feat: rotate snap indicator and snap rotated items

- src/board/UBBoardController.cpp
- src/board/UBBoardController.h
- src/board/UBBoardView.cpp
- src/domain/UBGraphicsScene.cpp
- src/domain/UBGraphicsScene.h
- src/gui/UBBoardThumbnailsView.cpp
This PR fixes the small shift of scenes when switching pages initially reported in #1009. Even if the effects of this problem depend on the Qt version use, it is an unclean procedure in the OpenBoard code that causes this.
There are two methods to move the visible region of a `QGraphicsView`:
- We can change the value of the horizontal and vertical scroll bar. These values are integers, so we can only move by pixels.
- Or we can change the transformation matrix of the view. This is the transformation from scene coordinates to view coordinates and everything is floating point here.
OpenBoard uses both, and that is not a good idea:
- When using the Hand tool, only the transform is changed.
- When using the zoom, transform and scrollbar values are changed.
- When using the mouse wheel, only …
> fix: small scene shifts when switching pages

- src/core/UBDocumentManager.cpp
This PR fixes #1156 where the first page of a PDF document was repeated at the end when importing the PDF by dropping it to the board.
- when importing a file to the board, the file was offered to all import adapters
- if multiple import adapters support the same file extension, then the file was imported multiple times
- this was especially true for pdf documents, where in some environments also the image adapter supported rendering a pdf document (preview image of first page)
- this commit leaves the loop iterating over the adapters once one of them has successfully imported the file
@sebojolais: could you test this PR whether it fixes the problem for you?
> fix: import file only once to document

- src/adaptors/UBThumbnailAdaptor.cpp
- src/adaptors/UBThumbnailAdaptor.h
- src/frameworks/CMakeLists.txt
- src/frameworks/UBBackgroundLoader.cpp
- src/frameworks/UBBackgroundLoader.h
- src/frameworks/frameworks.pri
- src/gui/UBThumbnailScene.cpp
- src/gui/UBThumbnailScene.h
This PR adds a background loader to read thumbnail files in another thread so that disk I/O, especially with a slow network drive, does not interfere with user actions.
The new class `UBBackgroundLoader` takes a list of file names and produces a list of results containing the data in these files in the same sequence. The I/O operations are performed on another thread.
The `UBThumbnailScene` is adapted to use the background loader for reading thumbnail file data. This avoids blocking operations on the main thread and improves user experiences during thumbnail loading.
> Performance: background loader

- src/adaptors/UBImportDocument.cpp
- after import of a UBZ file, the message showing the import progress was not muted
- add a success message without spinner at the end
> fix: spinning message after UBZ import

- src/core/UBPersistenceManager.cpp
- src/document/UBDocument.cpp
- src/frameworks/UBBackgroundLoader.cpp
- src/frameworks/UBBackgroundLoader.h
- src/gui/UBBoardThumbnailsView.cpp
- src/gui/UBBoardThumbnailsView.h
- src/gui/UBThumbnail.cpp
- src/gui/UBThumbnail.h
- src/gui/UBThumbnailScene.cpp
- src/gui/UBThumbnailScene.h
This PR fixes the issues described in https://github.com/letsfindaway/OpenBoard/issues/207.
Especially it makes sure that a thumbnail which we want to access is actually available even if background loading is still in progress. In this case such thumbnails are forced to be loaded in foreground.
It also makes sure a scene is saved before duplicating and fixes a bug where the scene and the thumbnail are not correlated after duplication.
Thumbnails are now updated independent whether they are exposed to the thumbnail view.
> Fix thumbnail sync

- src/gui/UBDocumentThumbnailsView.cpp
- src/gui/UBDocumentThumbnailsView.h
- src/gui/UBThumbnailScene.cpp
- src/gui/UBThumbnailScene.h
- fix access to still not loaded thumbnails
- either check for `nullptr`
- or load thumbnail before accessing
Fixes https://github.com/letsfindaway/OpenBoard/issues/209
> fix: possible crash in UBThumbnailScene

- src/core/UBPersistenceManager.cpp
- src/core/UBPersistenceManager.h
The method `createDocumentProxyStructure` doesn't depend on the object, so can be made static. QtConcurrent::mapped requires the argument of the method to be const, since it creates a new list for the mapping.
The lambda function marks its arguments as const by default. Since the method is now static, the lambda can be replaced with a direct reference.
The removal of the lambda resolves warning 3 of #1046.
> refactor(UBPersistenceManager): Make createDocumentProxyStructure static

- src/frameworks/UBBackgroundLoader.cpp
@kaamui 
Since #1268, a missing header leads to this cryptic error when building on Arch with Qt 6.9:
```
/build/openboard-git/src/OpenBoard/src/frameworks/UBBackgroundLoader.cpp: In destructor ‘virtual UBBackgroundLoader::~UBBackgroundLoader()’:
/build/openboard-git/src/OpenBoard/src/frameworks/UBBackgroundLoader.cpp:53:11: error: invalid use of incomplete type ‘class QDebug’
53 |     qDebug() << "Destruct UBBackgroundLoader";
|           ^
In file included from /usr/include/qt6/QtCore/qglobal.h:45,
from /usr/include/qt6/QtCore/qfuture.h:7,
from /usr/include/qt6/QtCore/QFuture:1,
from /build/openboard-git/src/OpenBoard/src/frameworks/UBBackgroundLoader.h:25,
from /build/openboard-git/src/OpenBoard/src/frameworks/UBBackgroundLoader.cpp:23:
/usr/include/qt6/QtCore/qtypeinfo.h:15:7: note: …
```
> Build failure: Add missing QDebug header
